# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39b1e5d5b68907131b924cfb9a2a6c1f9931e6edf532c52522710a35cf195073661cde28f6e638c15e3f321c22af35f53d622267cab5dad92a0d0e20ac79f9c
  admin_name: admin
  admin_email: josh@gotostepone.com
  admin_password: sunTzu74
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: santacruzdaily.com
  AWS_ACCESS_KEY_ID: AKIAJ6YVMALIMFSBQN6Q
  AWS_SECRET_ACCESS_KEY: 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
  FOG_PROVIDER: AWS
  FOG_DIRECTORY: stepone-scd
  FOG_REGION: us-west-1
  twitter_consumer_key: Cji4knBYbTlR4WSgH7MLRHoOM
  twitter_consumer_secret: LtqDn678ufllQ8rPemfM7k3npzEgS18nS9KZizop4aOpHzJn4a
  twitter_access_token: 281881640-6A0hYPAc9z7DATbiDMMfaAwnioksmI7766251jUu
  twitter_access_secret: 2LAHqei6QeLQAfNjkROstOY1j8QbkgUkdz820pb0hNdSN
  STRIPE_API_KEY: sk_test_W8RvelVgJxdVMlZoZhggagqm
  STRIPE_PUBLIC_KEY:  pk_test_jKrgScIgSSyVtMVh011wUj0O
  facebook_key: 737744139664460
  facebook_secret: 919cfbc55b3b7ed4c4eac2d093e95a70
  bing_api_key: As_QbhmBQSmae-4dwGTRBULHOUOBem9FFxCdmcrHE_MsCyllFdiuDKA09vhpqtv_

test:
  secret_key_base: 62fb692b9b49e18edc2b1ccbfe4a03b89d5a2208f5eb3116430ba33824b3f3c2c3e2bc968ff8dcfbfd08592b83e744b65933d2b4a1fe9e11f9e8e89ddbebb360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  MANDRILL_USERNAME: josh@gotostepone.com
  MANDRILL_API_KEY: kO0avNcDlHX7D7PdA3HuZg
  admin_name: admin
  admin_email: josh@gotostepone.com
  admin_password: sunTzu74
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: santacruzdaily.com
  AWS_ACCESS_KEY_ID: AKIAJ6YVMALIMFSBQN6Q
  AWS_SECRET_ACCESS_KEY: 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
  FOG_PROVIDER: AWS
  FOG_DIRECTORY: stepone-scd
  FOG_REGION: us-west-1
  twitter_consumer_key: Cji4knBYbTlR4WSgH7MLRHoOM
  twitter_consumer_secret: LtqDn678ufllQ8rPemfM7k3npzEgS18nS9KZizop4aOpHzJn4a
  twitter_access_token: 281881640-6A0hYPAc9z7DATbiDMMfaAwnioksmI7766251jUu
  twitter_access_secret: 2LAHqei6QeLQAfNjkROstOY1j8QbkgUkdz820pb0hNdSN
  STRIPE_API_KEY: sk_test_W8RvelVgJxdVMlZoZhggagqm
  STRIPE_PUBLIC_KEY:  pk_test_jKrgScIgSSyVtMVh011wUj0O
  facebook_key: 737744139664460
  facebook_secret: 919cfbc55b3b7ed4c4eac2d093e95a70
  bing_api_key: As_QbhmBQSmae-4dwGTRBULHOUOBem9FFxCdmcrHE_MsCyllFdiuDKA09vhpqtv_