# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39b1e5d5b68907131b924cfb9a2a6c1f9931e6edf532c52522710a35cf195073661cde28f6e638c15e3f321c22af35f53d622267cab5dad92a0d0e20ac79f9c

test:
  secret_key_base: 62fb692b9b49e18edc2b1ccbfe4a03b89d5a2208f5eb3116430ba33824b3f3c2c3e2bc968ff8dcfbfd08592b83e744b65933d2b4a1fe9e11f9e8e89ddbebb360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
